@startuml
         title 选择学期流程图
         actor 用户
         用户--> 学生 :登陆实验管理系统 （type：students)
         用户--> 教师: 登陆实验管理系统（type:teachers)
         学生-->学期:选择学期（若进行选课只能在当前学期选课）
         教师--> 学期:选择学期（若进行选课只能在当前学期选课）

@enduml