@startuml
actor 教师
教师 -> 系统: 成功登录该系统
教师 -> 课程:查看所教授全部课程，并选择欲添加实验课程
课程 -> 实验添加页:点击添加按实验按钮，输入实验要求及评分项

alt 所有实验添加成功
实验添加页 ->课程: 显示已添加实验
else 实验添加失败
实验添加页-->教师:提示实验添加失败
实验添加页-->课程:返回课程页面，提示请重新添加
end

@enduml